### ISSUE TITLE
Hay un par de imágenes que no funcionan

### ISSUE THREAD

**Issue by jllopezpino** [JJ/tuto-google-apps#1]
Hay un par de imágenes que no funcionan en http://jj.github.io/tuto-google-apps/:
http://jj.github.io/tuto-google-apps/img/registro.png
http://jj.github.io/tuto-google-apps/img/logger.png

Saludos!

**Comment by JJ** [comment]
Gracias por el issue. Lo corregiré.

2015-01-11 19:40 GMT+01:00 José Luis López Pino notifications@github.com:

> Hay un par de imágenes que no funcionan en
> http://jj.github.io/tuto-google-apps/:
> http://jj.github.io/tuto-google-apps/img/registro.png
> http://jj.github.io/tuto-google-apps/img/logger.png
> 
> Saludos!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/tuto-google-apps/issues/1.

## 

JJ
